#!/bin/sh

RET=0

# for i in $(git rev-list "$1".."$2")
for i in $(git diff --name-only)
do
    printf "Checking $i for values file ..."
    # if git log -1 --format="%B" $i | grep -qsE "[A-Z]+-[0-9]+"
    if echo $i | grep values
    then
        echo "looks ok."
    else
        echo "failed."
        RET=1
    fi
done

exit $RET