name: lint
on: pull_request
  # - branches: main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: chmod +x script/lint
    - run: sudo apt-get update
    - run:  sudo apt-get install python3.6
    - run: chmod +x script/python.py
    - run: brew install yq
    - run: script/lint 
    - run: python script/python.py