name: lint
on: pull_request
  # - branches: main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: chmod +x script/lint
    - run: script/lint "$GITHUB_SHA" "$GITHUB_REF"